import datetime, re

def get_dates_to_call_for_year(year, month, day):
    """
    takes a year, month, and day, and returns a list of dates, 7 before and 7 after, for that year, accounting for leap year and next/last year
    :param year:
    :param month:
    :param day:
    :return: a list of dates, 7 before and 7 after
    for each list [-1] would be the start date and [0] would be the end date
    """
    base = datetime.date(year, month, day)
    date_list = [base - datetime.timedelta(days=x+1) for x in range(-8, 7)]
    date_list_pretty = []
    for i in date_list:
        date_list_pretty.append(str(i))
    return date_list_pretty


def generate_master_date_list(month, day):
    """
    takes a month and a day and generates a list of lists,
    each list generated by get_dates_to_call_for_year
    :param month:
    :param day:
    :return: list of dates
    for each list in the list [-1] would be the start date and [0] would be the end date
    """
    current_year = str(datetime.datetime.today())
    # Added a -1 to account for a day of year that has not yet occurred for current year
    # this means we cannot look at the current year. Is this okay?
    year_only = int(re.findall(r"(\d{,4})-.+", current_year)[0])-1
    #do we want to use 1950? may need to look at request limits.
    #we might be fine with the past 25 years
    year_set = range(year_only, 1980, -1)
    master_date_list = []
    for year in year_set:
        single_year_dates = get_dates_to_call_for_year(year, month, day)
        #take the dates from
        master_date_list.append(single_year_dates)
    return master_date_list

if __name__ == '__main__':
    print(generate_master_date_list(6, 23))